### ISSUE TITLE
go1.12 got error parsing go.mod: unexpected module path "github.com/HdrHistogram/hdrhistogram-go"

### ISSUE THREAD

**Issue by wangzz719** [HdrHistogram/hdrhistogram-go#30]
This MR https://github.com/HdrHistogram/hdrhistogram-go/commit/bb05e18a12a6cbbdc359532a2f3c93d32f913404 changed module path, while using go mod in go1.12 occurs this error:

`go: github.com/codahale/hdrhistogram@v0.0.0-20200919145931-8dac23c8dac1: parsing go.mod: unexpected module path "github.com/HdrHistogram/hdrhistogram-go"`

**Comment by ahothan** [comment]
Hi, the original repository has been moved to a new github location, please update your src directory accordingly (you need to remove the old clone and issue another get from the new location).

**Comment by mammothbane** [comment]
This rename has caused transitive dependency issues. _Any_ module that depended on the old `codahale/hdrhistogram-go` (directly or not) is now broken and needs to update.

For instance, [jaegertracing/jaeger-client-go](https://github.com/jaegertracing/jaeger-client-go) depends on [jaegertracing/jaeger-lib](https://github.com/jaegertracing/jaeger-lib), which depends on `hdrhistogram` in [this testing code](https://github.com/jaegertracing/jaeger-lib/blob/c323da6d6a15d34312cc4d5a2db55c1adb20adf0/metrics/metricstest/local.go) (using the old `codahale` name).

The import in that file now breaks `go mod` because of the issue described in the OP -- the `codahale` version of the package can no longer be resolved, retroactive to all previously-published versions of this package. This is a breakage for everyone who depends on `jaeger-client-go`.

To resolve my problem in particular, I plan to PR the name change into `jaeger-lib` ASAP.

However, in case others aren't in direct control of their dependency on this module and are looking for a solution, you can use a `replace` directive in your `go.mod`, e.g.:

```
$ go mod edit -replace github.com/codahale/hdrhistogram=github.com/HdrHistogram/hdrhistogram-go@v0.0.0-20200919145931-8dac23c8dac1
```

**Comment by wangzz719** [comment]
I will have a try. Thanks!

**Comment by filipecosta90** [comment]
> For instance, [jaegertracing/jaeger-client-go](https://github.com/jaegertracing/jaeger-client-go) depends on [jaegertracing/jaeger-lib](https://github.com/jaegertracing/jaeger-lib), which depends on `hdrhistogram` in [this testing code](https://github.com/jaegertracing/jaeger-lib/blob/c323da6d6a15d34312cc4d5a2db55c1adb20adf0/metrics/metricstest/local.go) (using the old `codahale` name).

@mammothbane please check if this PR will fix the issue on jaeger-lib https://github.com/jaegertracing/jaeger-lib/pull/82
Also opening another one to fix jaeger-client-go

**Comment by mammothbane** [comment]
@filipecosta90 Thanks for doing this &mdash; and I'm sorry I didn't update my comment, but this has stopped breaking for me.

I was having issues for about 6 hours on Monday and I started making a PR myself, but on Tuesday morning, the issue spontaneously went away and I've been able to build again without any issues. I have no idea what changed &mdash; I had a pretty reproducible error &mdash; but I can't make it happen anymore.

If you're experiencing the problem, sorry, but I can no longer test a fix.
